name: Trigger auto deployment for c2c-python-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ app2 ]
    paths:
    - '**'
    - '.github/workflows/c2c-python-2-AutoDeployTrigger-0e6bdae8-92cd-4b14-b463-2d740b190ea4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.C2CPYTHON2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.C2CPYTHON2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.C2CPYTHON2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.C2CPYTHON2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.C2CPYTHON2_REGISTRY_PASSWORD }}
          containerAppName: c2c-python-2
          resourceGroup: simonj-c2ctest-3
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


